---
name: D

"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        dc:
          - dmd-latest
          - ldc-latest
          - dmd-beta
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dlang-community/setup-dlang@4c99aa991ce7d19dd3064de0a4f2f6b2f152e2d7
        with:
          compiler: ${{ matrix.dc }}
      - name: 'Test'
        run: |
          dub test
  docs:
    strategy:
      matrix:
        dc:
          - dmd-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dlang-community/setup-dlang@4c99aa991ce7d19dd3064de0a4f2f6b2f152e2d7
        with:
          compiler: dmd-latest
      - name: 'Build'
        run: |
          dub build -b ddox
          touch docs/.nojekyll
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: docs
